[versions]
minSdk = "24"
targetSdk = "34"
androidx-core-ktx = "1.12.0"
androidx-appcompat = "1.6.1"
android-material = "1.11.0"
android-constraintlayout = "2.1.4"
android-navigation-ui-ktx = "2.7.7"
android-navigation-fragment-ktx = "2.7.7"
junit = "4.13.2"
android-test-ext-junit = "1.1.5"
android-test-espresso-core = "3.5.1"

[libraries]
android-core-ktx = {module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx"}
android-appcompat = {module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat"}
android-material = {module = "com.google.android.material:material", version.ref = "android-material"}
android-constraintlayout = {module = "androidx.constraintlayout:constraintlayout", version.ref = "android-constraintlayout"}
android-navigation-ui-ktx = {module = "androidx.navigation:navigation-ui-ktx", version.ref = "android-navigation-ui-ktx"}
android-navigation-fragment-ktx = {module = "androidx.navigation:navigation-fragment-ktx", version.ref = "android-navigation-fragment-ktx"}
junit = {module = "junit:junit", version.ref = "junit"}
android-test-ext-junit = {module = "androidx.test.ext:junit", version.ref = "android-test-ext-junit"}
android-test-espresso-core = {module = "androidx.test.espresso:espresso-core", version.ref = "android-test-espresso-core"}

[plugins]

[bundles]
navigation-all = ["android-navigation-ui-ktx", "android-navigation-fragment-ktx"]